"""Bigger password field

Revision ID: 3baedd847517
Revises: 4711f0fac6cf
Create Date: 2022-11-21 20:18:17.197220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baedd847517'
down_revision = '4711f0fac6cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
