"""Added Tags table

Revision ID: 4711f0fac6cf
Revises: cb018980b65e
Create Date: 2022-11-21 15:20:37.660839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4711f0fac6cf'
down_revision = 'cb018980b65e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
